openapi: 3.0.0

info:
  title: Login API
  version: 1.0.0
  description: |
    Login endpoint for user authentication.

servers:
  - url: https://target.com

paths:
  /login:
    post:
      summary: User login
      description: Authenticate using username and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: admin
                password:
                  type: string
                  format: password
                  example: P@ssw0rd
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Login successful
        '401':
          description: Invalid credentials
